name = "DirectoriesMM"
uuid = "25689b0a-9a0b-424c-bbb1-e75cce8a2a0d"
authors = ["hendri54 <hendricksl@protonmail.com> and contributors"]
version = "1.1"

[deps]
CommonLH = "96c8dc4a-d23f-53b2-b478-aad5d5ab80bd"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FilesLH = "69233b93-b644-4f5d-9b2e-8880c8b19068"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
